title: 一个简单的日志记录函数
path: content.html
created: 2012-11-30T01:30:14+08:00
modified: 2012-11-30T01:31:05+08:00
keywords: PHP,代码片段,snippet,工具,tool
tags: php,snippet,tool
summary: >
    <section>
    <p>简单实有的 PHP 日志记录函数</p>
    </section>
