# /data/config.yaml

title: caixw
subtitle: 好记性不如烂笔头
url: https://caixw.io  # 不包含最后的斜杠
uptime: 2016-03-06T00:00:01+08:00
language: zh-cmn-Hans
pageSize: 20
longDateFormat: 2006-01-02 15:04
shortDateFormat: 2006-01-02
beian: 	浙ICP备16000327号-1
theme: default
type: text/html

# 程序图标
icon:
  url: /favicon.png
  type: image/png
  sizes: 256x256

# 默认的作者信息
author:
  name: caixw
  url: https://caixw.io

# 导航菜单栏
menus:
  - url: /
    title: 首页
    text: 首页
    icon: home

  - url: /tags.html
    title: 标签
    text: 标签
    icon: tags

  - url: /archives.html
    title: 归档
    text: 归档
    icon: archive

  - url: /posts/2016/about.html
    title: 关于
    text: 关于
    icon: info-circle

  - url: https://github.com/caixw
    title: Github
    text: Github
    icon: github
    rel: me

# 归档
archive:
  type: year
  format: 2006 年

# atom 的配置，为空表示没有
atom:
  url: /atom.xml
  size: 20
  # type: application/atom+xml

# rss 的配置，为空表示没有
rss:
  url: /rss.xml
  size: 20
  # type: application/rss+xml

# sitemap 的配置，为空表示没有
sitemap:
  url: /sitemap.xml
  xslURL: /sitemap.xsl
  enableTag: true
  tagPriority: 0.5
  postPriority: 0.6
  tagChangefreq: monthly
  postChangefreq: weekly
  # type: application/xml

# opensearch 设置
opensearch:
  url: /opensearch.xml
  title: caixw.io 的搜索引擎
  shortName: caixw.io 的搜索引擎
  longName: caixw.io 的搜索引擎
  description: 由 caixw.io 提供的搜索引擎，可根据标题和内容搜索文章。
  # type: application/opensearchdescription+xml
