# /data/config.yaml

title: caixw
subtitle: 好记性不如烂笔头
url: https://caixw.io
uptime: 2016-03-06T00:00:01+0800
pageSize: 20
longDateFormat: 2006-01-02 15:04
shortDateFormat: 2006-01-02
beian: 	浙ICP备16000327号-1
theme: default

author: # 默认的作者信息
    name: caixw
    url: https://caixw.io # 不包含最后的斜杠

menus:  # 顶部的菜单栏内容
  - url: /tags.html
    title: 标签
    text: 标签
    icon: tags

  - url: /posts/2016/about.html
    title: 关于
    text: 关于
    icon: info-circle

  - url: https://github.com/caixw
    title: Github
    text: Github
    icon: github
    rel: me

atom:  # atom 的配置，为空表示没有
    url: /atom.xml
    size: 20

rss:   # rss 的配置，为空表示没有
    url: /rss.xml
    size: 20

sitemap: # sitemap 的配置，为空表示没有
    url: /sitemap.xml
    enableTag: true
    tagPriority: 0.5
    postPriority: 0.4
    tagChangefreq: "monthly"
    postChangefreq: "weekly"
