# /data/config.yaml

title: caixw
titleSeparator: " | "
subtitle: 好记性不如烂笔头
uptime: 2016-03-06T00:00:01+08:00
language: zh-cmn-Hans
pageSize: 20
longDateFormat: 2006-01-02 15:04
shortDateFormat: 2006-01-02
beian: 	浙ICP备16000327号-1
theme: default
outdated: 8760h # 24*365 小时，遵守 time.ParseDuration 语法
type: text/html

# 程序图标
icon:
  url: /favicon.png
  type: image/png
  sizes: 256x256


# 默认的作者信息
author:
  name: caixw
  url: https://caixw.io

# 默认的版权信息
license:
  text: 署名 4.0 国际 (CC BY 4.0)
  url: https://creativecommons.org/licenses/by/4.0/deed.zh
  rel: license
  title: 版本信息

# 导航菜单栏
menus:
  - url: /
    title: 首页
    text: 首页
    icon: home

  - url: /tags.html
    title: 标签
    text: 标签
    icon: tags

  - url: /archives.html
    title: 归档
    text: 归档
    icon: archive

  - url: /posts/2016/about.html
    title: 关于
    text: 关于
    icon: info

  - url: /rss.xml
    title: RSS
    text: RSS 订阅
    icon: rss


# 归档
archive:
  order: desc
  type: year
  format: 2006 年

# atom 的配置，为空表示没有
atom:
  url: /atom.xml
  size: 20
  type: application/atom+xml

# rss 的配置，为空表示没有
rss:
  url: /rss.xml
  size: 20
  type: application/rss+xml

# sitemap 的配置，为空表示没有
sitemap:
  url: /sitemap.xml
  xslURL: /sitemap.xsl
  priority: 0.5
  changefreq: monthly
  enableTag: true
  postPriority: 0.6
  postChangefreq: weekly
  type: application/xml

# opensearch 设置
opensearch:
  url: /opensearch.xml
  title: caixw.io 的搜索引擎
  shortName: caixw.io 的搜索引擎
  longName: caixw.io 的搜索引擎
  description: 由 caixw.io 提供的搜索引擎，可根据标题和内容搜索文章。
  type: application/opensearchdescription+xml

pages:
  archives:
    title: "归档"
    keywords: 归档,存档,archive,archive
    description: 归档内容

  posts: # 首页即列表页内容
    keywords: Go,caixw,caixw.io,技术,博客
    description: 技术类博客

  post:
    title: "%content%"

  links:
    title: 友情链接
    keywords: 友情链接,链接,好友,同类博客

  tags:
    title: 标签
    description: 所有的标签列表以及专题内容

  tag:
    title: "标签：%content%"

  search:
    title: "搜索：%content%"
    keywords: "搜索,search,%content%,query"
