title: macOS High Sierra 的锁屏功能
created: 2017-09-26T21:05:59+08:00
modified: 2017-09-26T21:05:59+08:00
keywords: macOS,High Sierra,OSX,Lock Screen,锁定屏幕,锁屏
tags: macos
summary: >
    <section>
    <p>今天升级到了 macOS 10.13，没体验到 APFS 带来的各种好处，倒是意外发现了一个期待已久的锁屏功能。在系统菜单里，默认快捷键为 <kbd>ctrl+cmd+q</kbd>。可能和部分程序有冲突，可以通过以下方式修改快捷键。</p>
    </section>

assets:
  - posts/2017/macos-high-sierra-lock-screen/setting.png
  - posts/2017/macos-high-sierra-lock-screen/system-menu.png
