title: 为网页添加一个回到顶部按钮
created: 2012-12-11T15:08:00+08:00
modified: 2012-12-11T15:08:00+08:00
keywords: javascript,代码片段,snippet,工具,tool
tags: javascript,snippet,tool
summary: >
    <section>
    <p>为页面生成一个返回顶部的按钮</p>
    </section>
