title: Referrer Policy 介绍
created: 2017-08-11T00:34:54+08:00
modified: 2017-08-11T01:09:56+08:00
keywords: HTTP,Security,安全,Referrer Policy,http header
tags: http,security
summary: >
    <section>
    <p>当用户在浏览器上点击一个链接时，会产生一个 HTTP 请求，用于获取新的页面内容，而在该请求的报头中，会包含一个 Referrer，用以指定该请求是从哪个页面跳转页来的，常被用于分析用户来源等信息。但是也有成为用户的一个不安全因素，比如有些网站直接将 sessionid 或是 token 放在地址栏里传递的，会原样不动地当作 Referrer 报头的内容传递给第三方网站。</p>
    </section>
