title: Go 的版本自动化
created: 2016-11-29T22:31:42+08:00
modified: 2016-12-04T23:53:31+08:00
keywords: Go,semver,版本号,自动化
tags: go,version,semver
summary: >
    <section>
    <p>Go 语言中如何自动生成版本号。</p>
    </section>
