title: Firefox 搜索框提示无法下载插件的一个可能错误
created: 2017-09-11T21:59:17+08:00
modified: 2017-09-18T22:30:29+08:00
keywords: Firefox,Opensearch,plugin,插件
tags: firefox,opensearch,plugin
summary: >
    <section>
    <p>Firefox 搜索框提示无法下载插件的一个可能错误。</p>
    </section>
